FROM lambgeo/lambda-gdal:3.2-python3.8

LABEL maintainer "developmentseed"
PYTHONIOENCODING="UTF-8"  

ENV PATH=/script:$PATH
ENV PYTHONPATH  "${PYTHONPATH}:/script"
COPY /python-scripts /script
WORKDIR /script

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install .

VOLUME /mnt/data
WORKDIR /mnt/data
