version: '3'
services:
  geokit.py:
    image: developmentseed/geokit:python.latest_2
    build:
      context: ./
      dockerfile: Dockerfile.python
    volumes:
      - ./:/mnt
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
