version: '3'
services:
  geokit.js:
    image: developmentseed/geokit:node
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - ./:/mnt
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  geokit.py:
    image: developmentseed/geokit:python
    build:
      context: ./
      dockerfile: Dockerfile.python
    volumes:
      - ./:/mnt
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  geokit.java:
    image: developmentseed/geokit:java
    build:
      context: ./
      dockerfile: Dockerfile.java
    volumes:
      - ./:/mnt
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
