version: 2.1

jobs:
  geokit:
    docker:
      - image: docker:17.05.0-ce-git

    parameters:
      docker_image:
        type: string

    environment:
      - PRODUCTION_BRANCH: develop

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - caches/geokit.<<parameters.docker_image>>.tar

      - run:
          name: Load docker <<parameters.docker_image>> image cache
          command: |
            docker load -i caches/geokit.<<parameters.docker_image>>.tar || true

      - run:
          name: Build application docker <<parameters.docker_image>> image
          command: |
            docker build --cache-from=geokit.<<parameters.docker_image>> -t geokit.<<parameters.docker_image>> -f Dockerfile.<<parameters.docker_image>> .

      - run:
          name: Save docker image <<parameters.docker_image>> cache
          command: |
            mkdir -p caches
            docker save -o caches/geokit.<<parameters.docker_image>>.tar geokit.<<parameters.docker_image>>

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - caches/geokit.<<parameters.docker_image>>.tar

      - deploy:
          name: Push api Docker <<parameters.docker_image>> image
          command: |
            if [[ "${CIRCLE_BRANCH}" == *"develop"*  ]] ; then
              VERSION=<<parameters.docker_image>>.latest
            else
              VERSION=<<parameters.docker_image>>."${CIRCLE_BRANCH/<<parameters.docker_image>>-/""}"
            fi

            docker tag geokit.<<parameters.docker_image>> developmentseed/geokit:${VERSION}

            docker login --username $DOCKER_USER --password $DOCKER_TOKEN

            docker push developmentseed/geokit:${VERSION}

workflows:
  build_python:
    jobs:
      - geokit:
          docker_image: python
          filters:
            branches:
              only:
                - /python-.*/
                - develop
  build_node:
    jobs:
      - geokit:
          docker_image: node
          filters:
            branches:
              only:
                - /node-.*/
                - develop
  build_java:
    jobs:
      - geokit:
          docker_image: java
          filters:
            branches:
              only:
                - /java-.*/
                - develop
