repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        language_version: python3.10
  - repo: 'https://github.com/psf/black'
    rev: 22.10.0
    hooks:
      - id: black
        args: [ '--safe' ]
        language_version: python3.10
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        language_version: python3.10
        args: [
          # E501 let black handle all line length decisions
          # W503 black conflicts with "line break before operator" rule
          # E203 black conflicts with "whitespace before ':'" rule
            '--ignore=E501,W503,E203,F841' ]
  - repo: 'https://github.com/pycqa/pydocstyle'
    # 6.1.1
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        language_version: python3.10
        args: [
          # Check for docstring presence only
            '--select=D1',
          # Don't require docstrings for tests
            '--match=(?!test).*\.py' ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
      - id: mypy
        verbose: true
        args: [ '--no-strict-optional', '--ignore-missing-imports' , '--show-error-codes']
        additional_dependencies: [ 'types-requests' ]
