name: CI

# On every pull request, but only on push to master
on:
  push:
    branches:
      - ml
      - main
      - master
    tags:
      - '*'
  pull_request:

jobs:
  py_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox codecov pre-commit

      # Run pre-commit (only for python-3.8)
      - name: run pre-commit
        run: |
          cd python-scripts/
          pre-commit run --all-files
